// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package socketio

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"sync"

	"github.com/golang/glog"
	"github.com/timpalpant/go-iex"
)

// The iexMsgTypeNamespace is a generic class built using Genny.
// https://github.com/cheekybits/genny
// Run "go generate" to re-generate the specific namespace types.

// Contains callbacks and the symbols they correspond to.
type subIexTOPS struct {
	Callback func(iex.TOPS)
	Symbols  map[string]struct{}
}

// Receives messages for a given namespace and forwards them to endpoints.
type IexTOPSNamespace struct {
	// Used to guard access to the fanout channels.
	sync.RWMutex

	// A set of symbols that this namespace is currently subscribed to.
	// This spans across subcriptions so that unsubscribing from a symbol
	// only occurs if there are no subscriptions listening for that symbol.
	symbols Subscriber
	// The ID to use for the next connection created.
	nextId int
	// Active subscriptions by ID.
	subscriptions map[int]*subIexTOPS
	// For encoding outgoing messages in this namespace.
	encoder Encoder
	// Used for sending messages to the Transport.
	writer io.Writer
	// The factory function used to generate subscribe/unsubscribe messages.
	// Subscribe and unsubscribe messages can differe by IEX namespace.
	subUnsubMsgFactory subUnsubMsgFactory
	// A function to be called when the namespace has no more endpoints.
	closeFunc func(string)
}

// Sends a subscribe message. This is performed when the number of subscriptions
// goes from 0 to 1.
func (i *IexTOPSNamespace) sendPacket(msgType MessageType) error {
	r, err := i.encoder.EncodePacket(Message, msgType)
	if err != nil {
		return err
	}
	buffer := &bytes.Buffer{}
	_, err = buffer.ReadFrom(r)
	_, err = buffer.WriteTo(i.writer)
	return err
}

// Encodes and sends a subscribe or unsubscribe message on the transport layer.
func (i *IexTOPSNamespace) sendSubUnsub(subUnsubMsg *IEXMsg) error {
	r, err := i.encoder.EncodeMessage(Message, Event, subUnsubMsg)
	if err != nil {
		return fmt.Errorf("Error encoding %+v: %s", subUnsubMsg, err)
	}
	buffer := &bytes.Buffer{}
	_, err = buffer.ReadFrom(r)
	_, err = buffer.WriteTo(i.writer)
	return err
}

// Given a string representing a JSON IEX message type, parse out the symbol and
// message and pass the message to each connection subscribed to the symbol.
func (i *IexTOPSNamespace) fanout(pkt PacketData) {
	// This "symbol only" struct is necessary because this class
	// is a genny generic. Therefore, even though all IEX messages
	// have a "symbol" field, iexMsgType.symbol is not type safe.
	var symbol struct {
		Symbol string
	}
	if err := ParseToJSON(pkt.Data, &symbol); err != nil {
		glog.Errorf("No symbol found for iexMsgType: %s - %v",
			err, pkt)
	}
	// Now that the symbol has been extraced, the specific message
	// can be extracted from the data.
	var decoded iex.TOPS
	if err := ParseToJSON(pkt.Data, &decoded); err != nil {
		glog.Errorf("Could not decode iexMsgType: %s - %v",
			err, pkt)
	}
	if glog.V(5) {
		glog.Infof("Extracted symbol: %v", symbol)
		glog.Infof("Extracted message: %v", decoded)
	}
	i.RLock()
	defer i.RUnlock()
	for _, sub := range i.subscriptions {
		if _, ok := sub.Symbols[(symbol.Symbol)]; ok {
			sub.Callback(decoded)
		}
	}
}

// Returns a method that is passed to new Connections, to be called when the
// connection is being closed.
func (i *IexTOPSNamespace) getCloseSubscriptionFunc(id int) func() {
	return func() {
		i.Lock()
		unsub := make([]string, 0)
		sub := i.subscriptions[id]
		// Unsubscribe from the subscription symbols. For any that are
		// no longer being listened to by any subscription, send an
		// unsubscribe event to IEX. If there are no more subscriptions
		// in the namespace, disconnect from the namespace.
		for key, _ := range sub.Symbols {
			i.symbols.Unsubscribe(key)
			if !i.symbols.Subscribed(key) {
				unsub = append(unsub, key)
			}
		}
		delete(i.subscriptions, id)
		i.Unlock()
		if len(unsub) > 0 {
			err := i.sendSubUnsub(i.subUnsubMsgFactory(
				Unsubscribe, unsub))
			if err != nil {
				glog.Errorf("Error unsubscrubing from %v: %s",
					unsub, err)
			}
		}
		if len(i.subscriptions) == 0 {
			i.closeFunc(msgTypeToNamespace["IexTOPS"])
		}
	}
}

// Receive messages for the passed in symbols using the passed in callback.
// Returns a close function that should be called when the client does not wish
// to receive any further messages. If symbols is empty, an error is returned.
func (i *IexTOPSNamespace) SubscribeTo(
	msgReceived func(msg iex.TOPS), symbols ...string) (func(), error) {
	if len(symbols) == 0 {
		return nil, errors.New(
			"Cannot call SubscribeTo with no symbols")
	}
	i.Lock()
	defer i.Unlock()
	// Connect to the namespace when adding the first subscription.
	if len(i.subscriptions) == 0 {
		i.sendPacket(Connect)
	}
	i.nextId++
	newSub := &subIexTOPS{
		Callback: msgReceived,
		Symbols:  make(map[string]struct{}),
	}
	if len(symbols) > 0 {
		for _, symbol := range symbols {
			newSub.Symbols[symbol] = struct{}{}
			i.symbols.Subscribe(symbol)
		}
		err := i.sendSubUnsub(i.subUnsubMsgFactory(Subscribe, symbols))
		if err != nil {
			return nil, err
		}
	}
	i.subscriptions[i.nextId] = newSub
	return i.getCloseSubscriptionFunc(i.nextId), nil
}

// Create a new namespace for a specific IEX endpoint. Because the IEX
// namespaces use different message types for representing the received data,
// these classes are represented as generics using Genny.
func NewIexTOPSNamespace(
	transport Transport, subUnsubMsgFactory subUnsubMsgFactory,
	closeFunc func(string)) *IexTOPSNamespace {
	namespace := msgTypeToNamespace["IexTOPS"]
	encoder := NewWSEncoder(namespace)
	newNs := &IexTOPSNamespace{
		symbols:            NewCountingSubscriber(),
		nextId:             0,
		subscriptions:      make(map[int]*subIexTOPS),
		encoder:            encoder,
		writer:             transport,
		subUnsubMsgFactory: subUnsubMsgFactory,
		closeFunc:          closeFunc,
	}
	transport.AddPacketCallback(namespace, newNs.fanout)
	return newNs
}

// The iexMsgTypeNamespace is a generic class built using Genny.
// https://github.com/cheekybits/genny
// Run "go generate" to re-generate the specific namespace types.

// Contains callbacks and the symbols they correspond to.
type subIexLast struct {
	Callback func(iex.Last)
	Symbols  map[string]struct{}
}

// Receives messages for a given namespace and forwards them to endpoints.
type IexLastNamespace struct {
	// Used to guard access to the fanout channels.
	sync.RWMutex

	// A set of symbols that this namespace is currently subscribed to.
	// This spans across subcriptions so that unsubscribing from a symbol
	// only occurs if there are no subscriptions listening for that symbol.
	symbols Subscriber
	// The ID to use for the next connection created.
	nextId int
	// Active subscriptions by ID.
	subscriptions map[int]*subIexLast
	// For encoding outgoing messages in this namespace.
	encoder Encoder
	// Used for sending messages to the Transport.
	writer io.Writer
	// The factory function used to generate subscribe/unsubscribe messages.
	// Subscribe and unsubscribe messages can differe by IEX namespace.
	subUnsubMsgFactory subUnsubMsgFactory
	// A function to be called when the namespace has no more endpoints.
	closeFunc func(string)
}

// Sends a subscribe message. This is performed when the number of subscriptions
// goes from 0 to 1.
func (i *IexLastNamespace) sendPacket(msgType MessageType) error {
	r, err := i.encoder.EncodePacket(Message, msgType)
	if err != nil {
		return err
	}
	buffer := &bytes.Buffer{}
	_, err = buffer.ReadFrom(r)
	_, err = buffer.WriteTo(i.writer)
	return err
}

// Encodes and sends a subscribe or unsubscribe message on the transport layer.
func (i *IexLastNamespace) sendSubUnsub(subUnsubMsg *IEXMsg) error {
	r, err := i.encoder.EncodeMessage(Message, Event, subUnsubMsg)
	if err != nil {
		return fmt.Errorf("Error encoding %+v: %s", subUnsubMsg, err)
	}
	buffer := &bytes.Buffer{}
	_, err = buffer.ReadFrom(r)
	_, err = buffer.WriteTo(i.writer)
	return err
}

// Given a string representing a JSON IEX message type, parse out the symbol and
// message and pass the message to each connection subscribed to the symbol.
func (i *IexLastNamespace) fanout(pkt PacketData) {
	// This "symbol only" struct is necessary because this class
	// is a genny generic. Therefore, even though all IEX messages
	// have a "symbol" field, iexMsgType.symbol is not type safe.
	var symbol struct {
		Symbol string
	}
	if err := ParseToJSON(pkt.Data, &symbol); err != nil {
		glog.Errorf("No symbol found for iexMsgType: %s - %v",
			err, pkt)
	}
	// Now that the symbol has been extraced, the specific message
	// can be extracted from the data.
	var decoded iex.Last
	if err := ParseToJSON(pkt.Data, &decoded); err != nil {
		glog.Errorf("Could not decode iexMsgType: %s - %v",
			err, pkt)
	}
	if glog.V(5) {
		glog.Infof("Extracted symbol: %v", symbol)
		glog.Infof("Extracted message: %v", decoded)
	}
	i.RLock()
	defer i.RUnlock()
	for _, sub := range i.subscriptions {
		if _, ok := sub.Symbols[(symbol.Symbol)]; ok {
			sub.Callback(decoded)
		}
	}
}

// Returns a method that is passed to new Connections, to be called when the
// connection is being closed.
func (i *IexLastNamespace) getCloseSubscriptionFunc(id int) func() {
	return func() {
		i.Lock()
		unsub := make([]string, 0)
		sub := i.subscriptions[id]
		// Unsubscribe from the subscription symbols. For any that are
		// no longer being listened to by any subscription, send an
		// unsubscribe event to IEX. If there are no more subscriptions
		// in the namespace, disconnect from the namespace.
		for key, _ := range sub.Symbols {
			i.symbols.Unsubscribe(key)
			if !i.symbols.Subscribed(key) {
				unsub = append(unsub, key)
			}
		}
		delete(i.subscriptions, id)
		i.Unlock()
		if len(unsub) > 0 {
			err := i.sendSubUnsub(i.subUnsubMsgFactory(
				Unsubscribe, unsub))
			if err != nil {
				glog.Errorf("Error unsubscrubing from %v: %s",
					unsub, err)
			}
		}
		if len(i.subscriptions) == 0 {
			i.closeFunc(msgTypeToNamespace["IexLast"])
		}
	}
}

// Receive messages for the passed in symbols using the passed in callback.
// Returns a close function that should be called when the client does not wish
// to receive any further messages. If symbols is empty, an error is returned.
func (i *IexLastNamespace) SubscribeTo(
	msgReceived func(msg iex.Last), symbols ...string) (func(), error) {
	if len(symbols) == 0 {
		return nil, errors.New(
			"Cannot call SubscribeTo with no symbols")
	}
	i.Lock()
	defer i.Unlock()
	// Connect to the namespace when adding the first subscription.
	if len(i.subscriptions) == 0 {
		i.sendPacket(Connect)
	}
	i.nextId++
	newSub := &subIexLast{
		Callback: msgReceived,
		Symbols:  make(map[string]struct{}),
	}
	if len(symbols) > 0 {
		for _, symbol := range symbols {
			newSub.Symbols[symbol] = struct{}{}
			i.symbols.Subscribe(symbol)
		}
		err := i.sendSubUnsub(i.subUnsubMsgFactory(Subscribe, symbols))
		if err != nil {
			return nil, err
		}
	}
	i.subscriptions[i.nextId] = newSub
	return i.getCloseSubscriptionFunc(i.nextId), nil
}

// Create a new namespace for a specific IEX endpoint. Because the IEX
// namespaces use different message types for representing the received data,
// these classes are represented as generics using Genny.
func NewIexLastNamespace(
	transport Transport, subUnsubMsgFactory subUnsubMsgFactory,
	closeFunc func(string)) *IexLastNamespace {
	namespace := msgTypeToNamespace["IexLast"]
	encoder := NewWSEncoder(namespace)
	newNs := &IexLastNamespace{
		symbols:            NewCountingSubscriber(),
		nextId:             0,
		subscriptions:      make(map[int]*subIexLast),
		encoder:            encoder,
		writer:             transport,
		subUnsubMsgFactory: subUnsubMsgFactory,
		closeFunc:          closeFunc,
	}
	transport.AddPacketCallback(namespace, newNs.fanout)
	return newNs
}

// The iexMsgTypeNamespace is a generic class built using Genny.
// https://github.com/cheekybits/genny
// Run "go generate" to re-generate the specific namespace types.

// Contains callbacks and the symbols they correspond to.
type subIexDEEP struct {
	Callback func(iex.DEEP)
	Symbols  map[string]struct{}
}

// Receives messages for a given namespace and forwards them to endpoints.
type IexDEEPNamespace struct {
	// Used to guard access to the fanout channels.
	sync.RWMutex

	// A set of symbols that this namespace is currently subscribed to.
	// This spans across subcriptions so that unsubscribing from a symbol
	// only occurs if there are no subscriptions listening for that symbol.
	symbols Subscriber
	// The ID to use for the next connection created.
	nextId int
	// Active subscriptions by ID.
	subscriptions map[int]*subIexDEEP
	// For encoding outgoing messages in this namespace.
	encoder Encoder
	// Used for sending messages to the Transport.
	writer io.Writer
	// The factory function used to generate subscribe/unsubscribe messages.
	// Subscribe and unsubscribe messages can differe by IEX namespace.
	subUnsubMsgFactory subUnsubMsgFactory
	// A function to be called when the namespace has no more endpoints.
	closeFunc func(string)
}

// Sends a subscribe message. This is performed when the number of subscriptions
// goes from 0 to 1.
func (i *IexDEEPNamespace) sendPacket(msgType MessageType) error {
	r, err := i.encoder.EncodePacket(Message, msgType)
	if err != nil {
		return err
	}
	buffer := &bytes.Buffer{}
	_, err = buffer.ReadFrom(r)
	_, err = buffer.WriteTo(i.writer)
	return err
}

// Encodes and sends a subscribe or unsubscribe message on the transport layer.
func (i *IexDEEPNamespace) sendSubUnsub(subUnsubMsg *IEXMsg) error {
	r, err := i.encoder.EncodeMessage(Message, Event, subUnsubMsg)
	if err != nil {
		return fmt.Errorf("Error encoding %+v: %s", subUnsubMsg, err)
	}
	buffer := &bytes.Buffer{}
	_, err = buffer.ReadFrom(r)
	_, err = buffer.WriteTo(i.writer)
	return err
}

// Given a string representing a JSON IEX message type, parse out the symbol and
// message and pass the message to each connection subscribed to the symbol.
func (i *IexDEEPNamespace) fanout(pkt PacketData) {
	// This "symbol only" struct is necessary because this class
	// is a genny generic. Therefore, even though all IEX messages
	// have a "symbol" field, iexMsgType.symbol is not type safe.
	var symbol struct {
		Symbol string
	}
	if err := ParseToJSON(pkt.Data, &symbol); err != nil {
		glog.Errorf("No symbol found for iexMsgType: %s - %v",
			err, pkt)
	}
	// Now that the symbol has been extraced, the specific message
	// can be extracted from the data.
	var decoded iex.DEEP
	if err := ParseToJSON(pkt.Data, &decoded); err != nil {
		glog.Errorf("Could not decode iexMsgType: %s - %v",
			err, pkt)
	}
	if glog.V(5) {
		glog.Infof("Extracted symbol: %v", symbol)
		glog.Infof("Extracted message: %v", decoded)
	}
	i.RLock()
	defer i.RUnlock()
	for _, sub := range i.subscriptions {
		if _, ok := sub.Symbols[(symbol.Symbol)]; ok {
			sub.Callback(decoded)
		}
	}
}

// Returns a method that is passed to new Connections, to be called when the
// connection is being closed.
func (i *IexDEEPNamespace) getCloseSubscriptionFunc(id int) func() {
	return func() {
		i.Lock()
		unsub := make([]string, 0)
		sub := i.subscriptions[id]
		// Unsubscribe from the subscription symbols. For any that are
		// no longer being listened to by any subscription, send an
		// unsubscribe event to IEX. If there are no more subscriptions
		// in the namespace, disconnect from the namespace.
		for key, _ := range sub.Symbols {
			i.symbols.Unsubscribe(key)
			if !i.symbols.Subscribed(key) {
				unsub = append(unsub, key)
			}
		}
		delete(i.subscriptions, id)
		i.Unlock()
		if len(unsub) > 0 {
			err := i.sendSubUnsub(i.subUnsubMsgFactory(
				Unsubscribe, unsub))
			if err != nil {
				glog.Errorf("Error unsubscrubing from %v: %s",
					unsub, err)
			}
		}
		if len(i.subscriptions) == 0 {
			i.closeFunc(msgTypeToNamespace["IexDEEP"])
		}
	}
}

// Receive messages for the passed in symbols using the passed in callback.
// Returns a close function that should be called when the client does not wish
// to receive any further messages. If symbols is empty, an error is returned.
func (i *IexDEEPNamespace) SubscribeTo(
	msgReceived func(msg iex.DEEP), symbols ...string) (func(), error) {
	if len(symbols) == 0 {
		return nil, errors.New(
			"Cannot call SubscribeTo with no symbols")
	}
	i.Lock()
	defer i.Unlock()
	// Connect to the namespace when adding the first subscription.
	if len(i.subscriptions) == 0 {
		i.sendPacket(Connect)
	}
	i.nextId++
	newSub := &subIexDEEP{
		Callback: msgReceived,
		Symbols:  make(map[string]struct{}),
	}
	if len(symbols) > 0 {
		for _, symbol := range symbols {
			newSub.Symbols[symbol] = struct{}{}
			i.symbols.Subscribe(symbol)
		}
		err := i.sendSubUnsub(i.subUnsubMsgFactory(Subscribe, symbols))
		if err != nil {
			return nil, err
		}
	}
	i.subscriptions[i.nextId] = newSub
	return i.getCloseSubscriptionFunc(i.nextId), nil
}

// Create a new namespace for a specific IEX endpoint. Because the IEX
// namespaces use different message types for representing the received data,
// these classes are represented as generics using Genny.
func NewIexDEEPNamespace(
	transport Transport, subUnsubMsgFactory subUnsubMsgFactory,
	closeFunc func(string)) *IexDEEPNamespace {
	namespace := msgTypeToNamespace["IexDEEP"]
	encoder := NewWSEncoder(namespace)
	newNs := &IexDEEPNamespace{
		symbols:            NewCountingSubscriber(),
		nextId:             0,
		subscriptions:      make(map[int]*subIexDEEP),
		encoder:            encoder,
		writer:             transport,
		subUnsubMsgFactory: subUnsubMsgFactory,
		closeFunc:          closeFunc,
	}
	transport.AddPacketCallback(namespace, newNs.fanout)
	return newNs
}
